---
- name: Uninstall
  include_tasks: uninstall.yml
  when: purpose == 'uninstall' or purpose == 'reinstall'

- name: Install rpm and redis
  include_tasks: installtools.yml
  when: purpose == 'install'

- name: Upgrde redis
  include_tasks: upgrade.yml
  when: purpose == 'upgrade'

- name: create linux user
  shell: |
    groupadd --system redis
    useradd -s /sbin/nologin --system -g redis redis
  ignore_errors: yes
  when: purpose == 'install'

- name: Generate redis config file
  include_tasks: prepareredisconfig.yml
  when: purpose != 'uninstall'

- name: Generate service file
  include_tasks: prepareservice.yml
  when: purpose == 'install' or purpose == 'reinstall'

- name: Restart Service
  debug:
    msg: restart service
  notify: restart-service
  changed_when: true
  when: purpose == 'restart'

- meta: flush_handlers

- name: Run cluster creation script
  include_tasks: createcluster.yml
  run_once: true
  when: purpose == 'install' or purpose == 'reinstall'

# - name: show message
#   #run_once: true
#   debug: 
#     msg: install redis